### ISSUE TITLE
What's the recommended configuration to get Testify working on AWS Device Farm?

### ISSUE THREAD

**Issue by kpateldev** [ndtp/android-testify#109]

**Comment by DanielJette** [comment]
Hi @kpateldev 

### Follow Instrumentation Test and Espresso Test best practices

At its core, Android Testify is an extension to standard [Android Instrumentation Tests](https://developer.android.com/training/testing/instrumented-tests). As such, you are able to use many commonly available testing tools in conjunction with Android Testify. To begin, I would recommend that you read about the [AWS support for Android Instrumentation Tests](https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-instrumentation.html). Additionally, Android Testify is fully compatible with [Espresso Tests](https://developer.android.com/training/testing/espresso). As such, many tutorials on configuring Espresso will apply just as well to Testify. I'd recommend that you follow a tutorial, such as [this one](https://aws.amazon.com/blogs/mobile/getting-started-with-android-testing-on-aws-device-farm-using-espresso-part-1-building-a-sample-application/), to get your tests up & running on Device Farm.

### Disable Animations

Per the [Android documentation for Espresso testing](http://developer.android.com/training/testing/ui-testing/espresso-testing.html), it is recommended that system animations are turned off when testing. Device Farm automatically disables Window Animation Scale, Transition Animation Scale, and Animator Duration Scale settings when it executes with the [android.support.test.runner.AndroidJUnitRunner](http://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner.html) instrumentation test runner.

### Write to the SDCard

According to the [documentation](http://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-instrumentation.html) we need to save screenshots to the SD Card in order for them to be seen after a Run. You can follow [this guide](https://ndtp.github.io/android-testify/docs/recipes/sdcard) to configure Testify to write to the SDCard.

### Chose the right device configuration

As for the best device configuration for using Android Testify, this depends on your specific testing needs and requirements. In general, it is recommended to use an emulator that closely matches the configuration of a typical device that your end users will be using. You may even want to consider using a combination of different emulator configurations. If you don't have any specific device requirements, I would recommend that you start by selecting a device configuration that matches the [recommended Testify emulator settings](https://ndtp.github.io/android-testify/docs/get-started/configuring-an-emulator). I would also highly recommend that you select a virtual device for your testing and not a real physical device. Testify performs very well on an emulator and the extra cost of running on a real physical device is not justifiable.
Also consider that you will want to pick a device configuration that you are able to reproduce locally, on your team's development hardware. This will allow you to record your baseline images locally.

### Contribute back to Testify

If you are successful in deploying Testify to AWS Device Farm, I would love to hear more about your experience. Any additional information, tips or tricks that you could provide to other Testify users would be invaluable. Please consider sharing your feedback with us!

**Comment by kpateldev** [comment]
Thanks for all the details! 

AWS Device Farm only runs on physical devices. When running against an emulator with the same configurations as the physical device, I am noticing tests fail because of a screen offset diff like this - is there a suggested workaround for this?

![IMG_1784](https://user-images.githubusercontent.com/57636867/216852741-8c333269-99c0-4a4f-b01c-af89c3f86e3d.JPG)

**Comment by DanielJette** [comment]
@kpateldev The most common cause for the differences like you have shared are due to the impact of hardware acceleration of the graphics pipeline. On Android, this particularly impacts:

1. Shadows & elevation
1. Font smoothing & anti-aliasing
1. Image decompression and rendering
1. Alpha-blending

From the sample image you've attached, those look like prime candidates for your issue.

In this case, I would recommend:

1. If you have not already, [enable](https://ndtp.github.io/android-testify/docs/recipes/capture-method) the [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) capture method. It is a much more modern and effective method of capturing bitmaps.
2. [Decrease the matching _exactness_ tolerance. ](https://ndtp.github.io/android-testify/docs/recipes/tolerance). Despite what the documentation says, the tolerance code has been multithreaded recently and so it's not that much slower than a direct match. I'd recommend starting with a tolerance of `0.7f` and progressively raising the exactness in increments of `0.05f` until your tests no longer pass (then go back to the last level that worked). At low exactness values (less than `0.5`), the tolerance for differences starts to be so forgiving that even some layout and copy changes will be ignored. In most cases, an exactness value in the range of `0.75` through to `0.99` is safe to use for most layouts. If you use a lot of low-contrast UI (light-on-light or dark-on-dark), then you'll want to use higher values. The tolerance uses a [delta-E](https://www.viewsonic.com/library/creative-work/what-is-delta-e-and-why-is-it-important-for-color-accuracy/) algorithm for comparing images, so it's specifically designed to ignore minor color variations but will fail on changes to positioning, size or layout of elements.

Here is an example of what this would look like with 0.8f tolerance:

```kotlin
    @Before
    fun setUp() {
        TestifyFeatures.PixelCopyCapture.setEnabled(true)
        rule.setExactness(0.8f)
    }
```

**Comment by kpateldev** [comment]
Thank you! I was not using PixelCopy, and that seems to help.

Lastly, it looks like [AWS device farm ](https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-instrumentation.html) requires screenshots to be stored in one of the specific location patterns -
/sdcard/robotium-screenshots
/sdcard/test-screenshots
/sdcard/Download/spoon-screenshots/test-class-name/test-method-name
/data/data/application-package-name/app_spoon-screenshots/test-class-name/test-method-name

is there a way currently to have testify place screenshots in a custom location?

**Comment by philipsawyer** [comment]
Hi @DanielJette! Thank you for the helpful information above as we are working on this approach as well. 

I wanted to see if you had any pointers on recording screenshots. We were hoping to setup a workflow where developers would run a job on AWS DeviceFarm which would record the base screenshots. This would ensure all screenshots were recorded on the same device (and later validated against that same device). Do you know if there's a way to record screenshots on DeviceFarm? It looks like gradle is not available there but maybe there is a way to record using Instrumentation? 

Thanks for any help you can provide!

**Comment by DanielJette** [comment]
Hi @philipsawyer 
I can flesh this out in more detail later, but here's a couple of quick points that might help you get started

- Only the Testify library is required to record screenshots, not the Gradle plugin. The library has a "record mode" that can be set with an InstrumentationRegistry argument. If you set `isRecordMode` to `true`, Testify will perform the baseline recording operations
- Recorded baselines are stored on the virtual device. If you set up Testify to write to the SDCARD or with a [custom output](https://github.com/ndtp/android-testify/issues/109#issuecomment-1420903119), this is where you'll find the baseline images
- To glue all this together, we'll need to pass the argument through AWS and then download those images from AWS

Unfortunately, I haven't used AWS device farm in many, many years so I don't have any first-hand experience with this kind of setup. I'm not familiar with their configuration options, but theoretically this isn't an impossible task to pull off.

**Comment by philipsawyer** [comment]
Thank you for the help, @DanielJette! We were able to supply the `isRecordMode` Instrumentation option and got it working like we wanted.
