### ISSUE TITLE
Testify not working if Android is not on user 0

### ISSUE THREAD

**Issue by maurermax** [ndtp/android-testify#132]
I have issues running for example `screenshotRecord` in a multi-user environment.

It seems that the files are stored in local phone environment in the users data folder or emulated sdcard folder but the pull command is not able to find them there. 

On the debug LogCat one can see that the image is written to the non-0-user folder: `Writing screenshot to {/storage/emulated/10/Android/data/com....`

However in the pull of the images of the gradle command a `No failed screenshots found` appears. 

Everything works fine if I switch to user `0` before I start the testing flow.

**Comment by DanielJette** [comment]
Thanks for the feedback @maurermax 
I'd like to learn more about your use-case. Testify is not designed to work with multi-users because the envisioned use-case for Testify is for hermetic tests that target the view layer in isolation. Though Testify does interoperate with integration test frameworks (like Espresso), you'll find most of the features in Testify are oriented towards testing Views that are decoupled from their underlying logic. Injecting mocked or dummy data is the preferred option for ensuring fast, repeatable tests. I'm curious to know what scenarios you're using Testify with that result in having a non-0-user.

That said, read/write configuration for Testify can be customized with the `useSdCard` flag. Perhaps this alternative would work in your scenario?
https://testify.dev/docs/recipes/sdcard#configuring-testify-to-write-to-the-sdcard-using-an-environment-variable

**Comment by maurermax** [comment]
Thanks for the swift reply Daniel.

* In the environment where we test multi-user is enabled by default and the system standard user is actually not user 0 and instead user 10. 
* We do this for security reasons. For reasons of custom features in the emulator build we also need to test on this emulator and cannot get reliable test results if we just run the test in a "standard" emulator.

Regarding SD Card mode:
* I already found this option and tried it and it fails as well as the actual storage of the elements seems to go to a path something like `/storage/emulated/USER_ID/...` again which I think makes it faile due to the same reason as apparental virtual SD-Cards per user are used in our case

I also looked a bit into the code and I think it generally fails somewhere here:
https://github.com/ndtp/android-testify/blob/main/Plugins/Gradle/src/main/kotlin/dev/testify/internal/DeviceUtilities.kt#L56

I am not familiar with writing gradle tasks and I see that the file listing is already done as the package which makes me wonder why it shouuld not just work even if the package is installed under a different user. 

I could try and dig into this more and try and find a solution and provide a PR.

**Comment by DanielJette** [comment]
Hi @maurermax 
Thank you so much for providing this extra context. I really appreciate you taking the time to help.

There are possibly two places where there might be a bug.

1. The `Library` project runs in your `androidTest` process and is the one that writes files to the `data/data` directory.
2. The `Plugin` project runs on your client machine and synchronizes your local source code/version control with the emulated device's storage. 
 
They both need to agree on where to read/write the baseline images.

If you look [here](https://github.com/ndtp/android-testify/blob/178c3738f1c130a5cd29f9ab755c4a4de2e8c523/Library/src/androidTest/java/dev/testify/OutputFilePathTest.kt#L62) you'll see that my unit test assumes `user/0`. Testify gets this path from [this line](https://github.com/ndtp/android-testify/blob/main/Library/src/main/java/dev/testify/internal/output/OutputFileUtility.kt#L57).

Perhaps it's possible that the test process is running as a different user than the app? I'm not sure how that works.

The Plugin uses a `run-as` command on ADB in order to gain access to the `data/data` directory, so it's possible that the plugin is actually going to do the right thing on its own and the problem could be entirely in the `Library`.

I'm going to set up a multi-user configuration on my emulator this weekend and see if I can reproduce the issue. I would have expected the [`Context.getDir()`](https://developer.android.com/reference/android/content/Context#getDir(java.lang.String,%20int)) call to correctly return the proper user directory, so I'll have to see what's going on. I'm wondering if it's using the wrong `Context`.

**Comment by DanielJette** [comment]
@maurermax I'm still looking for the best way to address this issue. From my testing, I have narrowed down the issue to Testify's internal interactions with `adb`. I believe that the solution will be to somehow instruct Testify to use the `--user <userId>` argument when invoking `adb` commands, similar to what's documented [here](https://source.android.com/docs/devices/admin/multi-user-testing)

Do you have any suggestions on a configuration or workflow that you'd like to see? In particular, how would you like to tell Testify which user to use? Do you think a command-line flag would work? Would you like a `build.gradle` configuration setting? Or would you prefer to set that in the code, in your test?

**Comment by maurermax** [comment]
Hi @DanielJette thanks for looking into it so deeply. 

As far as I understood testifys main ways of configuring the behavior would be the Gradle testify block. 
So I could imagine a property there (most probably with 0 as the default). 
```
testify {
   emulator-user 0
}
````

Command line would also work fine for me. Maybe a combination of both would also be possible. Configuration+ command line where the command line overrides the configuration value. 

In the best case this would of course not need a configuration value at all but somehow discover a non non-default user on its own. 

`am shell current-user` spits out the currently running user which should also be the one that the deployment has deployed the package to.

**Comment by DanielJette** [comment]
Added with #144 
Available in Testify 2.0.0
