### ISSUE TITLE
Enable taking screenshots from dialogs

### ISSUE THREAD

**Issue by jdeebee** [ndtp/android-testify#176]
**Is your feature request related to a problem? Please describe.**
I was surprised to find out that Testify cannot verify/take a screenshot of dialogs. I believe this should be a core functionality of a snapshot testing library as dialogs are used in many apps and SDKs. I came across [this old issue](https://github.com/facebook/screenshot-tests-for-android/issues/70) from another library and [this Testify issue](https://github.com/ndtp/android-testify/issues/87) and now I understand why it's currently not possible, but it would be lovely if you could add a mechanism to take and verify a screenshot of a provided `Window` or `View` outside the activity view hierarchy. 

This feedback relates to:
- [ ] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**Describe the solution you'd like**
Introduce a way to take and verify a screenshot of a provided `Window` or `View` outside the activity view hierarchy

**Describe alternatives you've considered**
(Potentially) introduce an Espresso/AndroidX test rule for dialogs specifically

**Additional context**
N/A

**Comment by DanielJette** [comment]
@jdeebee Testify does not capture dialogs by default due to the way that Testify only captures a bitmap from the current Window. As Dialogs are rendered as separate windows, they require a use of a different capture method.

Fortunately, Testify does support capturing the entire screen, including Dialogs, through the user of the [FullscreenCapture method](https://ndtp.github.io/android-testify/docs/category/fullscreen-capture-method).

To capture dialogs with Testify:

1. [Add the `testify-fullscreen` extension library to your project 
](https://ndtp.github.io/android-testify/docs/extensions/fullscreen/setup)
2. Use the [`captureFullscreen()`](https://ndtp.github.io/android-testify/docs/extensions/fullscreen/test) modifier on your ScreenshotRule.
3. Exclude the System UI from the screenshot comparison using `excludeSystemUi`
4. Set the [`exactness` to a value](https://ndtp.github.io/android-testify/blog/platform-differences#enable-delta-e-comparison-with-an-exactness-value-of-less-than-1) of 0.95f or lower
5. Record & run your tests as usual

For more information, see the example [here](https://github.com/ndtp/android-testify/blob/main/Samples/Legacy/src/androidTest/java/dev/testify/sample/FullscreenCaptureExampleTests.kt#L47).

**Comment by jdeebee** [comment]
@DanielJette Great to hear this is already possible. Will try it today. Thanks for your quick answer!

**Comment by jdeebee** [comment]
@DanielJette I tried your suggested approach, however no system UI exclusion method is found in `ScreenshotRule` despite being mentioned in the documentation as well (none of `excludeStatusBar`, `excludeNavigationBar`, or `excludeSystemUi`). I tried the latest beta version (`beta4`) as well as `beta2`. Are these methods omitted by accident?

These are the versions I tried:
```
androidTestImplementation "dev.testify:testify-fullscreen:2.0.0-beta04"
androidTestImplementation "dev.testify:testify-fullscreen:2.0.0-beta02"
```

And this is how I configure the test rule:

```kotlin
ScreenshotRule(activityClass)
        .configure { exactness = 0.94f }
        .setCaptureMethod(::fullscreenCapture)
        .excludeStatusBar()
        .withExperimentalFeatureEnabled(TestifyFeatures.GenerateDiffs)
```

**Comment by DanielJette** [comment]
@jdeebee It does look like the documentation was not correctly updated for beta04
The exclusion extension methods were relocated to support on the new `TestifyConfiguration` class, but it seems like we missed updating the CHANGELOG and the Recipes. Sorry about this. I've logged a bug to address this here https://github.com/ndtp/android-testify/issues/181

In the meantime, you can use the `excludeStatusBar()`, `excludeNavigationBar()` or `excludeSystemUi()` via the `configure {}` closure.

```kotlin
@get:Rule val rule = ScreenshotRule(MainActivity::class.java)
rule
    .configure {
        exactness = 0.94f
        captureMethod = ::fullscreenCapture
        excludeStatusBar()
    }
    .withExperimentalFeatureEnabled(TestifyFeatures.GenerateDiffs)
    .assertSame()
```
